apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: nginx-port
    protocol: TCP
    port: 5000
    targetPort: nginx-port
  type: ClusterIP
  selector:
    app: nginx